sudo: required
services:
 - docker
before_install: 
 - docker build -t poonamtandon/react-test -f ./client/Dockerfile.dev ./client
script:
 - docker run poonamtandon/react-test npm test -- --coverage
after_success:
 - docker build -t poonamtandon/multi-client ./client
 - docker build -t poonamtandon/multi-nginx ./nginx
 - docker build -t poonamtandon/multi-server ./server 
 - docker build -t poonamtandon/multi-server ./worker

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
 - docker build -t poonamtandon/multi-client ./client
 - docker build -t poonamtandon/multi-nginx ./nginx
 - docker build -t poonamtandon/multi-server ./server 
 - docker build -t poonamtandon/multi-server ./worker